<%@ Page Title="" Language="C#" MasterPageFile="~/InputSite/Site1.Master" AutoEventWireup="true" CodeBehind="UserMainPage.aspx.cs" Inherits="CountyProject.UserMainPage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Welecome&nbsp&nbsp<asp:Label ID="userNameOutput" runat="server"></asp:Label></h1>
    <div id="adminUserControls" runat="server" visible="false">
        <asp:Button ID="mangageUsersButton" OnClick="ViewUsers" Text="Manage Users" runat="server" />
        <asp:GridView AutoGenerateDeleteButton="true" ID="usersView" OnRowCommand="SelectUser" 
            OnRowDeleting="DeletingUser" runat="server" Visible="false"></asp:GridView>
    </div>
    <p>Select a State:&nbsp&nbsp<asp:DropDownList AutoPostBack="true" ID="stateNames" OnTextChanged="StateSelected"
        runat="server"></asp:DropDownList></p>
    <asp:GridView ID="countiesView" runat="server" Visible="true"></asp:GridView>
    <asp:Button ID="takeTestButton" OnClick="TakeTest" Text="Start Test" runat="server" />
    <asp:Button ID="logoutButton" OnClick="Logout" Text="Logout" runat="server" />
</asp:Content>
